// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHOQt0PNU4cG2hyQfbUyoL9EkcKSe-44Y',
    appId: '1:29894037736:web:2f93de2a403bded506b95d',
    messagingSenderId: '29894037736',
    projectId: 'qlpj-c32e3',
    authDomain: 'qlpj-c32e3.firebaseapp.com',
    databaseURL: 'https://qlpj-c32e3-default-rtdb.firebaseio.com',
    storageBucket: 'qlpj-c32e3.firebasestorage.app',
    measurementId: 'G-DSLTXHF77W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8yzQPp6BtG6W57Xoe1B_YYibbKqg36Js',
    appId: '1:29894037736:android:dda7c21036f8d00406b95d',
    messagingSenderId: '29894037736',
    projectId: 'qlpj-c32e3',
    databaseURL: 'https://qlpj-c32e3-default-rtdb.firebaseio.com',
    storageBucket: 'qlpj-c32e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4X6pMTsRUDRRU4EZqB4tfF3KuLhSmZVQ',
    appId: '1:29894037736:ios:f425895279423e4b06b95d',
    messagingSenderId: '29894037736',
    projectId: 'qlpj-c32e3',
    databaseURL: 'https://qlpj-c32e3-default-rtdb.firebaseio.com',
    storageBucket: 'qlpj-c32e3.firebasestorage.app',
    iosBundleId: 'com.example.apkQlda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4X6pMTsRUDRRU4EZqB4tfF3KuLhSmZVQ',
    appId: '1:29894037736:ios:f425895279423e4b06b95d',
    messagingSenderId: '29894037736',
    projectId: 'qlpj-c32e3',
    databaseURL: 'https://qlpj-c32e3-default-rtdb.firebaseio.com',
    storageBucket: 'qlpj-c32e3.firebasestorage.app',
    iosBundleId: 'com.example.apkQlda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHOQt0PNU4cG2hyQfbUyoL9EkcKSe-44Y',
    appId: '1:29894037736:web:a19352070410746f06b95d',
    messagingSenderId: '29894037736',
    projectId: 'qlpj-c32e3',
    authDomain: 'qlpj-c32e3.firebaseapp.com',
    databaseURL: 'https://qlpj-c32e3-default-rtdb.firebaseio.com',
    storageBucket: 'qlpj-c32e3.firebasestorage.app',
    measurementId: 'G-TBX30F0JS8',
  );
}
